### ISSUE TITLE
Q: Does guix-rustup provide a packaging story?

### ISSUE THREAD

**Issue by PuercoPop** [declantsien/guix-rustup#2]
AFAIU guix-rustp main motivation is to use the rust-toolchain.toml to setup the rust toolchain needed to develop a crate. But how do we package the crate using guix?

**Comment by declantsien** [comment]
I thought I already included a procedure to use rust toolchain with Guix cargo-build-system. https://github.com/declantsien/guix-rustup/commit/9e0d279f807ba8806d06af316f307d42a7f2e5ad#diff-af5be99a72a1d828f22177d30a7bad6b1a52c1cc643975f6c4621b35518143ecR454

Will add some notes about it in README.

I have this `guix.scm` for my cargo project
```
(use-modules (guix)
	     (guix packages)
	     (guix gexp)
	     (guix git-download)   ;for ‘git-predicate’
	     (guix build-system cargo)
	     (rustup build toolchain)
	     (gnu packages crates-io)
	     (gnu packages llvm)	     
             ((guix licenses) #:prefix license:))

...

(define-public rust-cargo-ninja
  (package
    (name "rust-cargo-ninja")
    (version "0.5.1")
    (source (local-file "./" "rust-cargo-ninja-checkout"
			#:recursive? #t
			#:select? vcs-file?))
    (build-system (make-cargo-build-system "nightly-2024-01-25"))
    (native-inputs (list clang-toolchain-18))
    (arguments
     `(#:cargo-inputs (("rust-anyhow" ,rust-anyhow-1)
                       ("rust-camino" ,rust-camino-1)
                       ("rust-cargo-util" ,rust-cargo-util-0.2)
                       ("rust-cargo-util-schemas" ,rust-cargo-util-schemas-0.2)
                       ("rust-cargo-metadata" ,rust-cargo-metadata-0.18)
                       ("rust-clap" ,rust-clap-4)
                       ("rust-ninja-files-data2" ,rust-ninja-files-data2-0.1)
                       ("rust-ninja-files2" ,rust-ninja-files2-0.2)
                       ("rust-pathdiff" ,rust-pathdiff-0.2)
                       ("rust-serde" ,rust-serde-1)
                       ("rust-serde-derive" ,rust-serde-derive-1)
                       ("rust-serde-json" ,rust-serde-json-1)
                       ("rust-snailquote" ,rust-snailquote-0.3))))
    (home-page "")
    (synopsis "Generate build.ninja for Cargo build plan")
    (description "Generate build.ninja for Cargo build plan")
    (license license:expat))
  )

rust-cargo-ninja
```

**Comment by PuercoPop** [comment]
Thanks, that answers my question. guix-rustup provides a way to expose the information from the toolchain.toml file to guix's cargo-build-system.

Packaging dependencies is still something that one needs to handle on a package per package basis correct?

**Comment by declantsien** [comment]
> Thanks, that answers my question. guix-rustup provides a way to expose the information from the toolchain.toml file to guix's cargo-build-system.
> 
> 
> 
> Packaging dependencies is still something that one needs to handle on a package per package basis correct?

Most rust-* packages from Guix are functional as source. Using default cargo-build-system for source only package is fine. So you should only need to worry about the package you are currently working on.
